### ISSUE TITLE
Cypress-testing-library with typescript

### ISSUE THREAD

**Issue by YoavSch** [kentcdodds/cypress-testing-library#12]
Cypress-testing-library not working with typescript.

**Comment by YozhEzhi** [comment]
With Cypress-testing-library I haven't ability to fall in through to method declaration.
Native Cypress get method:
![](http://dl3.joxi.net/drive/2018/08/11/0024/1814/1611542/42/ca1115c919.jpg)

Cypress-testing-library helper:
![](http://dl3.joxi.net/drive/2018/08/11/0024/1814/1611542/42/de0c4ba907.jpg)

Are there some settings I should do to have ability to work with typings for Cypress-testing-library API?

**Comment by kentcdodds** [comment]
Sorry, I don't use typescript :-/ I don't know what could be wrong.

**Comment by sompylasar** [comment]
Wrong are missing typings for the mixed-in functions. Someone needs to adds typings to describe the additional functions this library attaches to the `cy` object.

**Comment by YozhEzhi** [comment]
I guess this typings will be enough.
https://github.com/kentcdodds/dom-testing-library/tree/master/typings

**Comment by sompylasar** [comment]
@YozhEzhi Yes, but not literally these files.

**Comment by aaronmcadam** [comment]
@sompylasar Do you know of a good way we can share the types from `dom-testing-library`, but add them to the `cy` object's interface?

**Comment by aaronmcadam** [comment]
@bahmutov Could you provide any guidance here?

**Comment by aaronmcadam** [comment]
I've tried the following, which at least stops the error showing up:

```ts

declare global {
  namespace Cypress {
    interface Chainable<Subject = any> {
      getByTestId<S = string>(x: string): Chainable<S>;
    }
  }
}
```

**Comment by sompylasar** [comment]
@aaronmcadam Try importing `queries` from `dom-testing-library` and make Cypress interface extend from it or somehow declare Cypress interface as an intersection type of the original interface and queries object. Maybe an interface containing all the functions will need to be declared in `dom-testing-library`, and exports declared to implement it, instead of plain `export function`. Don't know exactly how.

**Comment by sompylasar** [comment]
@aaronmcadam I gave it a secont thought, and the answer is **no, you should not reuse** from dom-testing-library because the function signatures differ (e.g the return value type). Copying and changing is the right way. Although maybe there is already an automated type mapping in recent TypeScript so maybe this can be used to map them.

**Comment by aaronmcadam** [comment]
Hi @sompylasar! Thanks for your thoughts, that helps a lot. I've started #16 to try to work out how to solve this. Could you take a look? I'm a bit unsure on how best to implement this in a maintainable way.

**Comment by sompylasar** [comment]
@aaronmcadam Reviewed, thanks.

> I'm a bit unsure on how best to implement this in a maintainable way.

Yes I'm not sure either. The functions from dom-testing-library are mapped dynamically into cypress commands (function wrappers) in cypress-testing-library by looping over the queries object here need static typing. Unless there's a way to statically map types of dom-testing-library functions into types of cypress-testing-library custom command functions, the list of functions will have to be maintained and kept in sync manually.

**Comment by freddydumont** [comment]
What's the status on this issue? Anything a non-typescript user can do to help? The problem I encounter is that it breaks the `cy` object auto-completion when chaining with this library.

**Comment by kentcdodds** [comment]
I'm not personally actively working on this issue. I don't track typescript issues very closely myself.

**Comment by aaronmcadam** [comment]
Hi @freddydumont I'm waiting on some feedback as to whether these types are correct. I do use TypeScript daily but I'd like some feedback from a maintainer

**Comment by aaronmcadam** [comment]
The PR is here: https://github.com/kentcdodds/cypress-testing-library/pull/16

**Comment by freddydumont** [comment]
Thanks for the replies guys. So who could review your PR? @sompylasar ?

**Comment by aaronmcadam** [comment]
Yeah it needs another look from him @freddydumont

**Comment by sompylasar** [comment]
@aaronmcadam @freddydumont Sorry haven't had time to look earlier, PR approved, assuming you checked that it works, I can't test it myself as I don't have a Cypress+TypeScript setup at hand.

**Comment by sompylasar** [comment]
Also the cypress-testing-library might need to be updated to the latest dom-testing-library, its public API has updated recently in some regards (don't remember if the changes affect the queries anyhow), please have a look at recent changes.
