### ISSUE TITLE
regex selector does not appear in cypress left panel

### ISSUE THREAD

**Issue by euZebe** [kentcdodds/cypress-testing-library#27]
* `cypress-testing-library` version: 2.3.4
* `node` version: 8.14.0
* `npm` version: 6.5.0

Relevant code or config

```javascript
    cy.queryByText(/basic/i).click(); // displays QUERYBYTEXT
    cy.queryByText("confirm").click(); // displays QUERYBYTEXT confirm
```
Problem description:
I guess this issue doesn't concern specifically a type of query, but rather its integration with cypress:
When using a regex to select any DOM element, I don't see the corresponding regex in the cypress panel, contrary to when I use a text selector.

![querybytext-text vs regex](https://user-images.githubusercontent.com/9463809/50076618-7e04ef00-01e2-11e9-86ba-36abb84425fa.png)

is it the expected behaviour? (Then why?)
Otherwise I would be delighted to try to fix the problem.

Suggested solution:
Display the stringified regex.

**Comment by kentcdodds** [comment]
That sounds like a bug, but I'm not sure what to do to fix it. Would you like to dig a little bit to see what is wrong?
